# Site settings
title: SQL and Database Management Using Pop Culture
description: An interactive textbook using pop culture references to simplify complex database concepts.

# Build settings
remote_theme: pages-themes/leap-day@v0.2.0
show_downloads: true

# Optional settings
author: Brendan P. Shea, PhD
email: brendanpshea@gmail.com
github_username:  brendanpshea
