title: SQL and Database Management Through Pop Culture
author: Brendan Shea, PhD
copyright: "2026"
logo: ""

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - colon_fence

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  extra_navbar: >-
    Supported with grant funding from Minnesota State and Rochester Community and Technical College.

repository:
  url: https://github.com/brendanpshea/database_sql
  branch: main
  path_to_book: .

launch_buttons:
  colab_url: https://colab.research.google.com
  notebook_interface: classic
