title: SQL and Database Management Through Pop Culture
author: Brendan Shea, PhD
copyright: "2026"
logo: database_cover.jpg

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - colon_fence

html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false
  extra_navbar: >-
    Supported with grant funding from Minnesota State and Rochester Community and Technical College.

sphinx:
  config:
    html_static_path:
      - _static
    html_css_files:
      - custom.css
    html_js_files:
      - sandbox-html-output.js

repository:
  url: https://github.com/brendanpshea/database_sql
  branch: main
  path_to_book: .

launch_buttons:
  colab_url: https://colab.research.google.com
  notebook_interface: classic
